# Generated by Django 5.1.2 on 2024-11-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=20, unique=True)),
                ('correo_electronico', models.EmailField(max_length=250)),
                ('fecha_nacimiento', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Argumento_Videojuego',
            fields=[
                ('id_argumento', models.AutoField(primary_key=True, serialize=False)),
                ('argumento', models.CharField(max_length=700)),
            ],
            options={
                'db_table': 'argumento_videojuego',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DecisionRecomendacion',
            fields=[
                ('id_opcion', models.AutoField(primary_key=True, serialize=False)),
                ('recomendacion_aceptada', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'decision_recomendacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EscalaPregunta',
            fields=[
                ('id_escala', models.AutoField(primary_key=True, serialize=False)),
                ('escala', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'escala_pregunta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_genero', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Motivacion_Jugador',
            fields=[
                ('id_motiv_jugador', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'motivacion_jugador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id_nacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('bandera', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'nacionalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id_plataforma', models.AutoField(primary_key=True, serialize=False)),
                ('consola', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'plataforma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preguntas_Motivacion',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'preguntas_motivacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recomendacion_Usuario',
            fields=[
                ('id_recomend_usuario', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'recomendacion_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id_videojuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500, unique=True)),
                ('portada', models.CharField(max_length=250)),
                ('genero', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
                ('empresa_desarrollo', models.CharField(max_length=500)),
                ('distribuidor', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'videojuego',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Videojuego_Especialidad',
            fields=[
                ('id_videojuego_especialidad', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'videojuego_especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Videojuego_Plataforma',
            fields=[
                ('id_videojuego_plataforma', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'videojuego_plataforma',
                'managed': False,
            },
        ),
    ]
