# Generated by Django 5.1.2 on 2024-11-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_gm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DecisionRecomendacion',
            fields=[
                ('id_opcion', models.AutoField(primary_key=True, serialize=False)),
                ('recomendacion_aceptada', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'decision_recomendacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EscalaPregunta',
            fields=[
                ('id_escala', models.AutoField(primary_key=True, serialize=False)),
                ('escala', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'escala_pregunta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id_nacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('bandera', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'nacionalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id_plataforma', models.AutoField(primary_key=True, serialize=False)),
                ('consola', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'plataforma',
                'managed': False,
            },
        ),
    ]
