# Generated by Django 5.1.2 on 2024-11-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_gm', '0002_categoria_decisionrecomendacion_escalapregunta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'especialidad',
                'managed': False,
            },
        ),
    ]
