# Generated by Django 5.1.2 on 2024-11-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_gm', '0003_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id_videojuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500, unique=True)),
                ('portada', models.CharField(max_length=250)),
                ('genero', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
                ('empresa_desarrollo', models.CharField(max_length=500)),
                ('distribuidor', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'videojuego',
                'managed': False,
            },
        ),
    ]
