# Generated by Django 5.1.2 on 2024-11-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_gm', '0004_videojuego'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argumento_Videojuego',
            fields=[
                ('id_argumento', models.AutoField(primary_key=True, serialize=False)),
                ('argumento', models.CharField(max_length=700)),
            ],
            options={
                'db_table': 'argumento_videojuego',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preguntas_Motivacion',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'preguntas_motivacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Videojuego_Plataforma',
            fields=[
                ('id_videojuego_plataforma', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'videojuego_plataforma',
                'managed': False,
            },
        ),
    ]
