# Generated by Django 5.1.2 on 2024-11-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_gm', '0006_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivacion_Jugador',
            fields=[
                ('id_motiv_jugador', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'motivacion_jugador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recomendacion_Usuario',
            fields=[
                ('id_recomend_usuario', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'recomendacion_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Videojuego_Especialidad',
            fields=[
                ('id_videojuego_especialidad', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'videojuego_especialidad',
                'managed': False,
            },
        ),
    ]
