# Generated by Django 5.1.2 on 2024-11-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_gm', '0007_motivacion_jugador_recomendacion_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
    ]
