# Generated by Django 5.1.2 on 2024-11-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_gm', '0008_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
